version: '3.8'

services:
  # Nginx (统一入口，HTTP-only)
  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_HTTP_PORT}:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  # Nginx配置
      - ./nextcloud/data:/var/www/html/data:ro  # 只读挂载Nextcloud文件
    depends_on:
      - nextcloud
      - onlyoffice
      - dozzle
      - jitsi-web
    networks:
      - unistack_network

  # Nextcloud (使用 PostgreSQL 15)
  nextcloud:
    image: nextcloud:latest
    environment:
      - POSTGRES_HOST=nextcloud_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./nextcloud/data:/var/www/html/data
      - ./nextcloud/config:/var/www/html/config
    networks:
      - unistack_network
    depends_on:
      - nextcloud_db

  # PostgreSQL 15 (最新稳定版)
  nextcloud_db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./nextcloud/postgres:/var/lib/postgresql/data
    networks:
      - unistack_network

  # OnlyOffice
  onlyoffice:
    image: onlyoffice/documentserver
    networks:
      - unistack_network
    volumes:
      - ./onlyoffice/data:/var/www/onlyoffice/Data

  # Dozzle 日志系统
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_BASE=/logs
    networks:
      - unistack_network
      
  # Jitsi Meet 组件
  # XMPP 服务器
  prosody:
    image: jitsi/prosody:stable-7001
    restart: unless-stopped
    volumes:
      - ./jitsi/prosody/config:/config
      - ./jitsi/prosody/prosody-plugins-custom:/prosody-plugins-custom
    environment:
      - XMPP_DOMAIN=meet.jitsi
      # 添加以下必要的环境变量
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_MUC_DOMAIN=muc.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - JICOFO_COMPONENT_SECRET=${JICOFO_COMPONENT_SECRET}
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
    networks:
      - unistack_network

  # 会议焦点组件
  jicofo:
    image: jitsi/jicofo:stable-7001
    restart: unless-stopped
    volumes:
      - ./jitsi/jicofo:/config
    environment:
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_SERVER=prosody
      - JICOFO_COMPONENT_SECRET=${JICOFO_COMPONENT_SECRET}
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
    depends_on:
      - prosody
    networks:
      - unistack_network

  # 视频桥接器
  jvb:
    image: jitsi/jvb:stable-7001
    restart: unless-stopped
    ports:
      - "10000:10000/udp"
    volumes:
      - ./jitsi/jvb:/config
    environment:
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_SERVER=prosody
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
    depends_on:
      - prosody
    networks:
      - unistack_network

  # Jitsi Web 界面
  jitsi-web:
    image: jitsi/web:stable-7001
    restart: unless-stopped
    volumes:
      - ./jitsi/web:/config
    environment:
      - ENABLE_AUTH=0
      - PUBLIC_URL=http://your-domain.com/meet
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_SERVER=prosody
      - XMPP_BOSH_URL_BASE=http://prosody:5280
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      # 添加以下环境变量
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_MUC_DOMAIN=muc.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
    depends_on:
      - prosody
      - jicofo
      - jvb
    networks:
      - unistack_network

networks:
  unistack_network:
    name: unistack_network
    driver: bridge